-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  email text,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Organizations
create table organizations (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  slug text unique not null,
  avatar_url text
);

alter table organizations enable row level security;

-- Organization Members
create table organization_members (
  organization_id uuid references organizations(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  role text check (role in ('owner', 'admin', 'member')) default 'member' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  primary key (organization_id, user_id)
);

alter table organization_members enable row level security;

-- Posts
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content jsonb, -- For Rich Text Editor setup (e.g. Tiptap JSON)
  status text check (status in ('draft', 'scheduled', 'published', 'archived')) default 'draft' not null,
  organization_id uuid references organizations(id) on delete cascade not null,
  author_id uuid references profiles(id) on delete set null,
  
  -- Metadata for SEO/Social
  excerpt text,
  featured_image text
);

alter table posts enable row level security;

-- Post Distributions (Status per channel)
create table post_distributions (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  channel text not null, -- 'webflow', 'linkedin_personal', 'linkedin_company', 'instagram', 'facebook', 'tiktok', 'youtube'
  status text check (status in ('pending', 'processing', 'published', 'failed')) default 'pending' not null,
  external_id text, -- ID in the external system
  published_at timestamp with time zone,
  error_message text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table post_distributions enable row level security;

-- Triggers for User Creation
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
